baseURL = "https://flwr.dev/"
languageCode = "en-us"
title = "/HOME/FLWR.DEV"
theme = "nord"
DefaultContentLanguage = "en"

[params]
  author = "Florian Weingartshofer"
  description = "flwr.dev ğŸ§ğŸ§"

[languages]
  [languages.en]
    weight = 1

[[menu.main]]
  identifier = "flwr"
  name = "/HOME/FLWR.DEV"
  url = "/"
  weight = 10
[[menu.main]]
  identifier = "wiki"
  name = "Wiki"
  url = "/wiki/"
  weight = 20
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 30