baseURL = "http://flwr.dev/"
languageCode = "en-us"
title = "/HOME/FLWR.DEV"
theme = "nord"
DefaultContentLanguage = "en"

[params]
  author = "Florian Weingartshofer"
  description = "flwr.dev ğŸ§ğŸ§ğŸ§"

[languages]
  [languages.en]
    weight = 1
